"""change_embedding_dim_3072_to_1024

Revision ID: 03e4d2b1e3fa
Revises: 0cdbb36aa121
Create Date: 2026-03-01 06:25:10.840804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '03e4d2b1e3fa'
down_revision: Union[str, None] = '0cdbb36aa121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear existing embeddings (3072-dim) so the column type can be changed.
    # Documents will need to be re-embedded with DashScope text-embedding-v3.
    op.execute("UPDATE document_chunks SET embedding = NULL")
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###
